// <auto-generated />
namespace TradingView.DAL.Migrations
{
	using System.Data.Entity.Migrations.Infrastructure;
	using System.Resources;


	public sealed partial class Initial : IMigrationMetadata
	{
		private readonly ResourceManager Resources = new ResourceManager(typeof(Initial));
		
		string IMigrationMetadata.Id
		{
			get { return "201901272144292_Initial"; }
		}
		
		string IMigrationMetadata.Source
		{
			get { return null; }
		}
		
		string IMigrationMetadata.Target
		{
			get { return Resources.GetString("Target"); }
		}
	}
}
