// <auto-generated />
namespace TradingView.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddQuoteAndSymbolModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddQuoteAndSymbolModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201901271901044_AddQuoteAndSymbolModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
